apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels: 
    app: app
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: app
  template:
    metadata: 
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: mattregojos/app:latest
        ports:
        - containerPort: 9000
        env:
        - name: DB_NAME
          valueFrom:
            secretKeyRef: 
              name: my-secret
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef: 
              name: my-secret
              key: DB_USER
        - name: DB_HOST
          valueFrom:
            secretKeyRef: 
              name: my-secret
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            secretKeyRef: 
              name: my-secret
              key: DB_PORT
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef: 
              name: my-secret
              key: DB_PASSWORD
        - name: PROJECT_NAME
          valueFrom:
            secretKeyRef: 
              name: my-secret
              key: PROJECT_NAME
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef: 
              name: my-secret
              key: ADMIN_PASSWORD
        - name: APP_PORT
          valueFrom:
            secretKeyRef: 
              name: my-secret
              key: APP_PORT
        - name: APP_ADDRESS
          valueFrom:
            secretKeyRef: 
              name: my-secret
              key: APP_ADDRESS
        - name: DOMAIN_NAME
          valueFrom:
            secretKeyRef: 
              name: my-secret
              key: DOMAIN_NAME
        - name: SPECIAL_NAME
          valueFrom:
            secretKeyRef: 
              name: my-secret
              key: SPECIAL_NAME
    
